### ISSUE TITLE
Plugin update needed for InteliJ 2021.2

### ISSUE THREAD

**Issue by DSEyers** [ChrisCarini/environment-variable-settings-summary-intellij-plugin#11]
Plugin not compatable with InteliJ IDEA 2021.2 build 212.4746.92

**Comment by ChrisCarini** [comment]
Hi @DSEyers - thank you for reporting this issue. A version should now be released to the plugin marketplace - you should now be able to update the plugin from within your IDE.

I'm going to go ahead and close this issue out, please feel free to reopen if you are still having issues.

**Comment by DSEyers** [comment]
Thanks
