### ISSUE TITLE
Run configuration template settings are not present in new configurations

### ISSUE THREAD

**Issue by DarrenBishop** [ChrisCarini/environment-variable-settings-summary-intellij-plugin#87]
Often you click the green 'Play' arrow in IntelliJ to run a test ad-hoc; this is effectively broken if the test needs environment variables setup in order to run successfully.

Setting up the EnvFile entry in the ScalaTest run configuration template should resolve that issue, however, the templates presets do not carry over to new run configurations.

I would say we lose half the benefit of this plugin due to this.

Is this an easy one to fix?

**Comment by ChrisCarini** [comment]
Hmm, do you happen to have a reproducible test case I can try (with detailed steps)?

My expectation is that this plugin should not modify the actual environment for run configurations, but rather will only (1) provide a setting summary containing environment variables and (2) allow users to hide environment variables from showing in the aforementioned settings summary as they see fit.

Happy to take a further look if you can provide me a detailed reproducible case (ie, git repo to clone, steps to setup run configuration, what you'd expect, and what happens).

Let me know!

**Comment by DarrenBishop** [comment]
I’m so sorry, I’ve filed the bug under the entirely wrong plugin.

I also use the Env File plugin at
https://plugins.jetbrains.com/plugin/7861-envfile
I will file the bug there.

Again, apologies

Sent from my iPhone
...

**Comment by ChrisCarini** [comment]
@DarrenBishop - no worries. That plugin makes a lot more sense! I will go ahead and close out this issue for this project.
