### ISSUE TITLE
Needs update for GoLand 2022.2

### ISSUE THREAD

**Issue by fgm** [ChrisCarini/environment-variable-settings-summary-intellij-plugin#94]
On GoLand 2022.2 EAP / Build #GO-222.3244.4, built on June 29, 2022

"Incompatible: requires IDE build 221.* or earlier".

**Comment by ChrisCarini** [comment]
Hi @fgm - thank you for reporting this issue. Currently, I do not have capacity to support EAP builds for my JetBrains plugins.

Based on history, I'd expect the EAP to become a released version (ie, `2022.2.0`) the last week of the month; [GoLand](https://github.com/ChrisCarini/jetbrains-ide-release-dates/blob/main/ides/GoLand_Release_Dates.md) & [IntelliJ](https://github.com/ChrisCarini/jetbrains-ide-release-dates/blob/main/ides/IntelliJ_IDEA_Ultimate_Release_Dates.md) - I typically try to get my extensions updated and released within a few days of the RELEASE version of IntelliJ.

As a related aside, I am working on some automation that will hopefully enable me to release versions against EAPs (essentially, it's a very low ROI for me to manually make the needed updates and publish to the marketplace; I am trying to automate everything except a few clicks, which is more manageable for me). No ETA on that quite yet though.

Stay tuned! I will keep this issue open until I have a released version for you in the marketplace.

**Comment by ChrisCarini** [comment]
Closing issue, a version was released for 2022.2 a while ago; sorry for the delay in closing this issue.
